- ros_topic_name: "/camera"
  gz_topic_name: "/world/cbrn_world/model/cbrn_robot/link/base_link/sensor/camera_sensor/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: "GZ_TO_ROS"
